name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build (skip tests)
        run: ./mvnw -B package -DskipTests

      - name: Run Unit Tests
        run: ./mvnw -B test

      - name: Upload Surefire Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Publish Test Results to GitHub
        uses: dorny/test-reporter@v2
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: surefire
          fail-on-error: true