name: Continuous Integration

on:
  push:
    branches:
      - "**"   # all branches
  workflow_dispatch: # allows manual trigger for publishing Docker

jobs:
  deployment:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Publish Docker Image
        if: github.event_name == 'workflow_dispatch'
        env:
          REGISTRY_ADDR: ${{ secrets.REGISTRY_ADDR }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: ./mvnw -DskipTests jib:build
