name: CI/CD

on:
  push:
    branches-ignore:
      - "main"   # avoid double run when PR opened
  pull_request:
    branches:
      - "main"
  workflow_dispatch: # manual trigger for deploy

jobs:
  package:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build (skip tests)
        run: ./mvnw -B package -DskipTests

      - name: Run Unit Tests
        run: ./mvnw -B test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # run only when manually triggered

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Publish Docker Image
        env:
          REGISTRY_ADDR: ${{ secrets.REGISTRY_ADDR }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: ./mvnw -DskipTests jib:build

      - name: Deploy to AWS
        run: |
          echo "Deploying to AWS..."
