name: CI/CD Workflow

on:
  push:
    branches:
      - "**"   # all branches
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch: # allows manual trigger for publishing Docker

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: ./mvnw -B package -DskipTests

      - name: Run Unit Tests
        run: ./mvnw -B test

      - name: Update dependency graph (Dependabot)
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Build & Publish Docker Image
        if: github.event_name == 'workflow_dispatch'
        env:
          REGISTRY_ADDR: ${{ secrets.REGISTRY_ADDR }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: ./mvnw -DskipTests jib:build
